version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  admin:
    image: apache/dubbo-admin:latest
    depends_on:
      - zookeeper
    ports:
      - 8081:8080
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
# docker-compose -f /home/jun/docker/zookeeper/docker-compose.yaml up -d