server:
  port: 7000

spring:
  application:
    name: dubbo-consumer
logging:
  level:
    root: info

#dubbo
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://192.168.96.129:2181
    timeout: 60000
  protocal:
    name: dubbo
  consumer:
    retries: 1
    check: false
